# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/28harold04@gmail.com/VMC_MAISON/TRANSFORME/ChargerLogCapteur")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM workspace.default.sample_aggregation_chargerlogcapteur"))

# COMMAND ----------

import csv

with open('/Workspace/Users/28harold04@gmail.com/VMC_MAISON/SOURCES/20250811_134500', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter='\t')
    for row in spamreader:
        print('\t'.join(row))

# COMMAND ----------

import pandas as pd

logcapteur = pd.read_csv("/Workspace/Users/28harold04@gmail.com/VMC_MAISON/SOURCES/20250811_134500",delimiter='\t', header=None, )

logcapteur.head()

# COMMAND ----------

from datetime import datetime, timedelta
from pyspark.sql.functions import col, expr,regexp_replace,round

nomFichier = "20250811_134500"
source = "/Workspace/Users/28harold04@gmail.com/VMC_MAISON/SOURCES/" 
dateDebut = datetime.strptime(nomFichier, '%Y%m%d_%H%M%S')

df = spark.read.option("delimiter", "\t").csv( source + nomFichier, schema="chrono int, humidite int, temperature string")

df = df.withColumn("temperature",regexp_replace(col("temperature"), ",", ".").cast("float"))
df = df.withColumn("temperature",round(col("temperature"),2))

df = df.withColumn("chrono",expr(f"timestamp('{dateDebut}') + chrono * INTERVAL 1 SECOND"))

df.createOrReplaceTempView("df_log_vmc")

#df.show()
display(df)

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS log_vmc;
# MAGIC create table log_vmc as 
# MAGIC select
# MAGIC *
# MAGIC from df_log_vmc;

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from log_vmc;
